@startuml

skinparam style strictuml
autonumber

actor Consumer as user
participant Booking as book
participant CPMShandler as cpms

activate user
user -> book : get view
activate book
book --> user : view
deactivate book

alt user has more than one vehicle
    user -> book : selected station and vehicle
    activate book
else user has only one vehicle
    user -> book : station and vehicle
end
book -> cpms : get availabilities
activate cpms
cpms --> book : availabilities
deactivate cpms
book --> user : availabilities
deactivate book

user -> book : station, slot and vehicle
activate book
book -> cpms : send data
activate cpms
cpms --> book : booking recap
deactivate cpms
book --> user : 200 OK and notification
deactivate book
deactivate user

@enduml
