@startuml

skinparam style strictuml
autonumber

actor Consumer as consumer
participant DatabaseHandler as db
participant "Web server" as web
participant CPMShandler as cpms
participant User as user
participant VehicleHandler as vehicle
participant BookingHandler as booking
participant CPMSapi as api

activate consumer
consumer -> web : get view
activate web
web --> consumer : view
deactivate web

consumer -> web : get vehicle view
activate web
web --> consumer : view
deactivate web
consumer -> web : send updated data
activate web
web -> user : updateVehicle (user, vehicles, new)
activate user
user -> vehicle : updateVehicle (old, new)
activate vehicle
vehicle -> db : updateVehicle (old, new)
activate db
db --> vehicle : certificate
deactivate
vehicle --> user : certificate
deactivate vehicle
opt updated certificate
    user -> booking : updateBookingsFor (user, vehicleId, certificate)
    activate booking
    loop for every cpms
        booking -> cpms : getFutureBookings (user, vehicle)
        activate cpms
        cpms -> api : getFutureBookings (user)
        activate api
        api --> cpms : bookings
        deactivate api
        cpms -> cpms : filter (bookings, vehicle)
        activate cpms
        cpms --> cpms : bookings
        deactivate cpms
        cpms --> booking : bookings
        deactivate cpms
        loop for every booking
            booking -> cpms : updateBookingCertificate (booking, certificate)
            activate cpms
            cpms -> api : updateBookingCertificate (booking, certifica)
            activate api
            api --> cpms : ack
            deactivate api
            cpms --> booking : ack
            deactivate cpms
        end
    end
end
booking --> user : ack
deactivate booking
user -> user : createToken (user, vehicles)
activate user
user --> user : JWT
deactivate user
user --> web : JWT
deactivate user
web --> consumer : 200 Ok, JWT
deactivate web
deactivate consumer

@enduml
